CC     = gcc
CFLAGS = -std=c99

s1: status_test1.c
	$(CC) $(CFLAGS) status_test1.c -o status_test1

s2: status_test2.c
	$(CC) $(CFLAGS) status_test2.c -o status_test2

clean:
	rm -f a.out status_test1 status_test2
