CC     = gcc
CFLAGS = -std=c99 -pedantic -Werror -Wall

p1: func_ptr1.c
	$(CC) $(CFLAGS) func_ptr1.c -o func_ptr1
	
p2: func_ptr2.c
	$(CC) $(CFLAGS) func_ptr2.c -o func_ptr2

p3: func_ptr3.c
	$(CC) $(CFLAGS) func_ptr3.c -o func_ptr3

clean:
	rm -f a.out func_ptr1 func_ptr2 func_ptr3
